css two column layout | Humberto Navarro
humbertovnavarro/c0621-code-solutions pull request #22
Opened 2021-06-28 05:46 UTC by humbertovnavarro

2021-06-28 05:47 UTC, humbertovnavarro commented
![image](https://user-images.githubusercontent.com/16251746/123586473-496f4680-d7d4-11eb-9138-1757dbf7bcda.png)

2021-06-28 21:52 UTC, codingcodymiller requested changes
Hey Humberto! I can't see your entire output in your screenshot, please submit another image so that I can see the entire output

2021-06-28 21:57 UTC, humbertovnavarro commented
![image](https://user-images.githubusercontent.com/16251746/123709043-39318880-d821-11eb-9de3-ba2d116971d2.png)

2021-06-30 22:04 UTC, codingcodymiller requested changes
Hey Humberto! The two columns have too much space between each other and the rows above and below them as compared to the example. Please revise this to match the desired output

2021-07-01 02:45 UTC, humbertovnavarro commented
![image](https://user-images.githubusercontent.com/16251746/124057087-b1dc4480-d9db-11eb-9204-a70be665076e.png)

2021-07-01 21:46 UTC, codingcodymiller requested changes
Great start here! One minor note of housekeeping:

2021-07-01 21:46 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +  background-color :#d14c45;
The space between your property and the `:` here is messing up your syntax

2021-07-01 22:02 UTC, codingcodymiller requested changes

2021-07-01 22:02 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +  background-color :#d14c45;
You misunderstood, the selector was fine, I mean the space after `background-color`

2021-07-01 22:05 UTC, codingcodymiller approved these changes
Great work on this!!!

2021-07-01 22:05 UTC, merged